language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
services:
  - postgresql
before_install:
  - pip install pycodestyle codecov
  - python3 setup.py install
before_script:
  - psql -c 'create database my_db;' -U postgres
  - psql -f sample_table/schema.sql my_db -U postgres
script:
  - pycodestyle --exclude=venv --ignore=E501 .
  - pytest
  - coverage run --branch --source=. -m unittest discover -bv
  - coverage report -m
after_success:
  - codecov
